name: E2E Loan Application Test

on:
  workflow_dispatch:
    inputs:
      test_plan:
        description: "Test plan to execute"
        default: "e2e-personal-loan-application"
        type: choice
        options:
          - e2e-personal-loan-application
          - e2e-entity-loan-application
          - e2e-negative-edge-cases
  schedule:
    - cron: "0 0 * * *"

jobs:
  personal-loan:
    if: github.event_name == 'schedule' || inputs.test_plan == 'e2e-personal-loan-application'
    uses: ./.github/workflows/run-test.yml
    with:
      test_plan: e2e-personal-loan-application
      trigger_type: ${{ github.event_name }}
    secrets: inherit

  entity-loan:
    if: github.event_name == 'schedule' || inputs.test_plan == 'e2e-entity-loan-application'
    uses: ./.github/workflows/run-test.yml
    with:
      test_plan: e2e-entity-loan-application
      trigger_type: ${{ github.event_name }}
    secrets: inherit

  negative-edge:
    if: github.event_name == 'schedule' || inputs.test_plan == 'e2e-negative-edge-cases'
    uses: ./.github/workflows/run-test.yml
    with:
      test_plan: e2e-negative-edge-cases
      trigger_type: ${{ github.event_name }}
    secrets: inherit
